version: "3.1"
services:
    web:
      container_name: rtm
      build: RTM-Chat/
      labels:
          SERVICE_80_NAME: rtm
          SERVICE_TAG : rtm
      restart: always
      depends_on:
        - mongo
      volumes:
        - "/machine_config:/app/machine_config"
    mongo:
      image: mongo:4.1
      restart: always
      volumes:
        - "/data/rtm:/var/lib/mongodb"